runtime: nodejs18

env: standard

instance_class: F1

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  SUPABASE_URL: "https://api.altumlaboratories.com"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94aWpoaXFmd21ocnN5aWtscGJqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4ODk4OTQwMiwiZXhwIjoyMDA0NTY1NDAyfQ.jJomizQIf043ePptKN6xP38_1kWRMy4Eh11pWJowR94"
  STRIPE_SECRET_KEY: "sk_test_51MhgZ7Ef36GHXrtikPWGeFnmPibkYvm0x62URux3bAIY3NkONfayDZfTtQeXmchsTY85bSadb1oS8Qq7YmOmymxH00doHjxFCX"
  STRIPE_WEBHOOK_SECRET: "whsec_GNVfWQqxjfqScAGKFCEiirjeVE3pz4Yz"
  SUCCESS_URL: "/dashboard/producer/orders"
  CANCEL_URL: "/dashboard/producer/new-order"
  FRONTEND_DOMAIN: "https://plantalysis.com"
