export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFteWdsdWJramx0bmFleGVieGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODg5ODk0MzIsImV4cCI6MjAwNDU2NTQzMn0.jeDqfEWYMwgdquOskcy1Nc7D-1fJ-3dhbXSXoPwas6o";
export const SUPABASE_URL = "https://amyglubkjltnaexebxid.supabase.co";
